[package]
name = "aoc2024"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
itertools = "0.13.0"
regex = "1.11.1"

[lib]
name = "lib"
path = "src/lib.rs"

[[bin]]
name = "1"
path = "src/01.rs"


[[bin]]
name = "2"
path = "src/02.rs"

[[bin]]
name = "3"
path = "src/03.rs"
